# **Intro Data**

In [ ]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('Realestate_edit.csv')
df

      No  date   age        dist  store       lat       long  price    Village
0      1  2012  32.0    84.87882     10  24.98298  121.54024   37.9  Dapinglin
1      2  2012  19.5   306.59470      9  24.98034  121.53951   42.2  Dapinglin
2      3  2013  13.3   561.98450      5  24.98746  121.54391   47.3  Dapinglin
3      4  2013  13.3   561.98450      5  24.98746  121.54391   54.8  Dapinglin
4      5  2012   5.0   390.56840      5  24.97937  121.54245   43.1  Dapinglin
..   ...   ...   ...         ...    ...       ...        ...    ...        ...
366  409  2013  18.5  2175.74400      3  24.96330  121.51243   28.1  New store
367  411  2012   5.6    90.45606      9  24.97433  121.54310   50.0  Dapinglin
368  412  2013  18.8   390.96960      7  24.97923  121.53986   40.6  Dapinglin
369  413  2013   8.1   104.81010      5  24.96674  121.54067   52.5  Dapinglin
370  414  2013   6.5    90.45606      9  24.97433  121.54310   63.9  Dapinglin

[371 rows x 9 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 371 entries, 0 to 370
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   No       371 non-null    int64
 1   date     371 non-null    int64
 2   age      371 non-null    float64
 3   dist     371 non-null    float64
 4   store    371 non-null    int64
 5   lat      371 non-null    float64
 6   long     371 non-null    float64
 7   price    371 non-null    float64
 8   Village  371 non-null    object
dtypes: float64(5), int64(3), object(1)
memory usage: 26.2+ KB

In [ ]:
frekuensi_distrik = df['Village'].value_counts()
print(frekuensi_distrik)

Dapinglin     258
New store     101
Pond            8
Fulfilling      4
Name: Village, dtype: int64

In [ ]:
import folium
import pandas as pd


# Initialize the map
LAT = df['lat']
LONG = df['long']
villages = df['Village'].unique()
peta = folium.Map(location=[df['lat'].mean(), df['long'].mean()], zoom_start=15)

unique_villages = df['Village'].unique()
colors = ['red', 'green', 'yellow', 'blue']

village_color_dict = {village: colors[i % len(colors)] for i, village in enumerate(unique_villages)}


for i in range(len(LAT)):
    village = df['Village'].iloc[i]
    color = village_color_dict[village]

    folium.CircleMarker(
        location=[LAT.iloc[i], LONG.iloc[i]],
        radius=5,  # Marker size
        color=color,  # Marker color
        fill=True,
        fill_color=color,
        fill_opacity=0.6,
        popup=f'Harga: {df["price"].iloc[i]:.2f}, \nDaerah: {village}'  # Information popup
    ).add_to(peta)

# Show the map
peta

In [ ]:
df

      No  date   age        dist  store       lat       long  price    Village
0      1  2012  32.0    84.87882     10  24.98298  121.54024   37.9  Dapinglin
1      2  2012  19.5   306.59470      9  24.98034  121.53951   42.2  Dapinglin
2      3  2013  13.3   561.98450      5  24.98746  121.54391   47.3  Dapinglin
3      4  2013  13.3   561.98450      5  24.98746  121.54391   54.8  Dapinglin
4      5  2012   5.0   390.56840      5  24.97937  121.54245   43.1  Dapinglin
..   ...   ...   ...         ...    ...       ...        ...    ...        ...
366  409  2013  18.5  2175.74400      3  24.96330  121.51243   28.1  New store
367  411  2012   5.6    90.45606      9  24.97433  121.54310   50.0  Dapinglin
368  412  2013  18.8   390.96960      7  24.97923  121.53986   40.6  Dapinglin
369  413  2013   8.1   104.81010      5  24.96674  121.54067   52.5  Dapinglin
370  414  2013   6.5    90.45606      9  24.97433  121.54310   63.9  Dapinglin

[371 rows x 9 columns]

In [ ]:
df = df.drop(['lat', 'long'], axis=1)

In [ ]:
dups=df.duplicated()
print(dups.any())

False

In [ ]:
df.columns

Index(['No', 'date', 'age', 'dist', 'store', 'price', 'Village'], dtype='object')

In [ ]:
filtered_data = df[(df['price'] >= 100) & (df['price'] < 120)]

print(filtered_data)

Empty DataFrame
Columns: [No, date, age, dist, store, price, Village]
Index: []

In [ ]:
filtered_data = df[(df['No'] == 357)]

print(filtered_data)

      No  date   age      dist  store  price    Village
317  357  2012  10.3  211.4473      1   45.3  Dapinglin

In [ ]:
df.describe()

,No,date,age,dist,store,price
count,371.000000,371.000000,371.000000,371.000000,371.000000,371.000000
mean,208.757412,2012.690027,17.475202,741.001846,4.493261,39.527763
std,120.433162,0.463107,11.742498,675.242324,2.780595,11.652456
min,1.000000,2012.000000,0.000000,23.382840,0.000000,7.600000
25%,104.500000,2012.000000,8.000000,279.172600,2.000000,30.650000
50%,210.000000,2013.000000,15.600000,461.784800,5.000000,40.000000
75%,313.000000,2013.000000,28.850000,1144.436000,7.000000,47.200000
max,414.000000,2013.000000,43.800000,3085.170000,10.000000,73.600000

In [ ]:
df.head()

   No  date   age       dist  store  price    Village
0   1  2012  32.0   84.87882     10   37.9  Dapinglin
1   2  2012  19.5  306.59470      9   42.2  Dapinglin
2   3  2013  13.3  561.98450      5   47.3  Dapinglin
3   4  2013  13.3  561.98450      5   54.8  Dapinglin
4   5  2012   5.0  390.56840      5   43.1  Dapinglin

In [ ]:
dummies = pd.get_dummies(df.Village)
dummies.head(3)

   Dapinglin  Fulfilling  New store  Pond
0          1           0          0     0
1          1           0          0     0
2          1           0          0     0

In [ ]:
df2 = pd.concat([df,dummies],axis='columns')
df2.head()

,No,date,age,dist,store,price,Village,Dapinglin,Fulfilling,New store,Pond
0,1,2012,32.0,84.87882,10,37.9,Dapinglin,1,0,0,0
1,2,2012,19.5,306.59470,9,42.2,Dapinglin,1,0,0,0
2,3,2013,13.3,561.98450,5,47.3,Dapinglin,1,0,0,0
3,4,2013,13.3,561.98450,5,54.8,Dapinglin,1,0,0,0
4,5,2012,5.0,390.56840,5,43.1,Dapinglin,1,0,0,0

In [ ]:
df3 = df2.drop('Village',axis='columns')
df3.head(2)

,No,date,age,dist,store,price,Dapinglin,Fulfilling,New store,Pond
0,1,2012,32.0,84.87882,10,37.9,1,0,0,0
1,2,2012,19.5,306.59470,9,42.2,1,0,0,0

In [ ]:
df3.shape

(371, 10)

In [ ]:
X1 = df3.drop(['price','No'],axis='columns')
X1.head(3)

   date   age       dist  store  Dapinglin  Fulfilling  New store  Pond
0  2012  32.0   84.87882     10          1           0          0     0
1  2012  19.5  306.59470      9          1           0          0     0
2  2013  13.3  561.98450      5          1           0          0     0

In [ ]:
y1 = df3.price
y1.head(3)

0    37.9
1    42.2
2    47.3
Name: price, dtype: float64

# **Test Linear Regression df**

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import pandas as pd

X1 = df3.drop(['price','No'],axis='columns')
y1 = df3.price

X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.2, random_state=0)

# Buat model regresi linear
reg = LinearRegression()
reg.fit(X1_train, y1_train)

# Prediksi harga
y1_pred = reg.predict(X1_test)

# Evaluasi model
print('Linear Regression')
print('RMSE:', mean_squared_error(y1_test, y1_pred))
print('MAE:', mean_absolute_error(y1_test, y1_pred))
print('R^2:', r2_score(y1_test, y1_pred))

Linear Regression
RMSE: 69.57198179272213
MAE: 5.874841434851
R^2: 0.4959532800418943

In [ ]:
df

      No  date   age        dist  store  price    Village
0      1  2012  32.0    84.87882     10   37.9  Dapinglin
1      2  2012  19.5   306.59470      9   42.2  Dapinglin
2      3  2013  13.3   561.98450      5   47.3  Dapinglin
3      4  2013  13.3   561.98450      5   54.8  Dapinglin
4      5  2012   5.0   390.56840      5   43.1  Dapinglin
..   ...   ...   ...         ...    ...    ...        ...
366  409  2013  18.5  2175.74400      3   28.1  New store
367  411  2012   5.6    90.45606      9   50.0  Dapinglin
368  412  2013  18.8   390.96960      7   40.6  Dapinglin
369  413  2013   8.1   104.81010      5   52.5  Dapinglin
370  414  2013   6.5    90.45606      9   63.9  Dapinglin

[371 rows x 7 columns]

In [ ]:
pred_df=pd.DataFrame({'Actual Value':y1_test,'Predicted Value':y1_pred,'Difference':y1_test-y1_pred})
pred_df

     Actual Value  Predicted Value  Difference
141          35.6        41.558573   -5.958573
142          39.4        47.045343   -7.645343
313          25.7        17.451098    8.248902
60           36.2        41.595282   -5.395282
302          42.9        36.290331    6.609669
..            ...              ...         ...
113          62.9        34.624182   28.275818
312          28.6        25.580647    3.019353
173          48.2        44.739707    3.460293
198          42.3        41.623656    0.676344
331          42.1        44.023933   -1.923933

[75 rows x 3 columns]

# **Test Linear Regression df_5**

In [ ]:
from sklearn.model_selection import train_test_split
X2 = df_5.drop(['No','price','lat','long'],axis=1) # data fitur/prediktor
y2 = df_5.price # target
X2_train, X2_test, y2_train, y2_test = train_test_split(X2,y2, test_size = 0.2,random_state = 0)

from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit (X2_train, y2_train)

reg.coef_

y2_pred = reg.predict(X2_test)

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
print('Linear Regression')
print('RMSE :', mean_squared_error(y2_test, y2_pred))
print('MAE :', mean_absolute_error(y2_test, y2_pred))
print('R :', r2_score(y2_test,y2_pred)*100,'%')

NameError: ignored

In [ ]:
pred_df=pd.DataFrame({'Actual Value':y2_test,'Predicted Value':y2_pred,'Difference':y2_test-y2_pred})
pred_df

# **Test Linear Regression df_4**

In [ ]:
from sklearn.model_selection import train_test_split
X3 = df_4.drop(['No','price','dist','lat','long'],axis=1) # data fitur/prediktor
y3 = df_4.price # target
X3_train, X3_test, y3_train, y3_test = train_test_split(X3,y3, test_size = 0.2,random_state = 0)

from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit (X3_train, y3_train)

reg.coef_

y3_pred = reg.predict(X3_test)

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
print('Linear Regression')
print('RMSE :', mean_squared_error(y3_test, y3_pred))
print('MAE :', mean_absolute_error(y3_test, y3_pred))
print('R :', r2_score(y3_test,y3_pred)*100,'%')

In [ ]:
pred_df=pd.DataFrame({'Actual Value':y3_test,'Predicted Value':y3_pred,'Difference':y3_test-y3_pred})
pred_df

In [ ]:
X3

In [ ]:
y3

# **Save/Import Model**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os

# Ganti path dengan direktori yang Anda inginkan
directory = "/content/drive/MyDrive/Model"

if not os.path.exists(directory):
    os.makedirs(directory)

import pickle
print("Saving")
path = "/content/drive/MyDrive/Model/realestate_LR.pickle"
pickle.dump(reg, open(path, "wb"))

Mounted at /content/drive
Saving

In [ ]:
import pickle

with open('/content/drive/MyDrive/Model/realestate_LR.pickle', 'rb') as file:
    loaded_model = pickle.load(file)

# **Input Model 1**

In [ ]:
import pandas as pd
import numpy as np
import pickle

# Load model regresi linear yang sudah dilatih
with open('/content/drive/MyDrive/Model/realestate_LR.pickle', 'rb') as file:
    loaded_model = pickle.load(file)

# Fungsi untuk memprediksi harga berdasarkan fitur yang diberikan
def predict_price_lr(date, age, dist, store, Dapinglin, Fulfilling, New_store, Pond):
    # Persiapkan data input dengan format yang sesuai dengan model regresi linear
    input_data = np.array([[date, age, dist, store, Dapinglin, Fulfilling, New_store, Pond]])

    # Lakukan prediksi harga menggunakan model regresi linear yang sudah dilatih
    predicted_price = loaded_model.predict(input_data)

    return predicted_price[0]

# **Input Model 2**

In [ ]:
import numpy as np

# Fungsi untuk memprediksi harga rumah dengan model MLP
def predict_price_lr(date,age,store,trans_dist):
    # Persiapkan data input dengan format yang sesuai dengan model MLP
    input_data = [[date,age,store,trans_dist]]

    # Lakukan prediksi dengan model MLP yang sudah dilatih (loaded_model)
    predicted_price = loaded_model.predict(input_data)

    return predicted_price[0]

# **Test Prediksi 1**

In [ ]:
filtered_data = df[(df['price'] == 35.6)]

print(filtered_data)

In [ ]:
predicted_price = predict_price_lr(2013, 16.1, 815.9314, 4, 1, 0, 0, 0)
print(predicted_price)

In [ ]:
predict_price_lr(2013, 32, 1500, 7)

# **Test Prediksi 2**

In [ ]:
filtered_data = df_4[(df_4['No'] == 357)]

print(filtered_data)

In [ ]:
predict_price_lr(2012, 10.3, 1, 5.353976)

# **ABSTRAK**

In [ ]:
def predict_price(village, date, age, dist, store):
    # Mencari indeks lokasi dalam kolom X
    loc_index = np.where(X1.columns == village)[0][0]

    # Membuat vektor input dengan nilai awal 0
    x = np.zeros(len(X1.columns))

    # Menetapkan nilai fitur sesuai dengan argumen fungsi
    x[0] = date
    x[1] = age
    x[2] = dist
    x[3] = store

    # Jika lokasi ditemukan dalam kolom X, atur nilai fitur sesuai indeks lokasi
    if loc_index >= 0:
        x[loc_index] = 1

    # Lakukan prediksi harga menggunakan model regresi linear (reg)
    predicted_price = reg.predict([x])[0]

    return predicted_price

In [ ]:
predicted_price = predict_price('Dapinglin', 2012, 32.0, 84.87882, 10)
print(predicted_price)

45.280629460632554

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [ ]:
X1

In [ ]:
y1

# **JSON**

In [ ]:
import json

# Menentukan path lengkap untuk file 'columns.json' di direktori '/content/drive/MyDrive/Model'
file_path = '/content/drive/MyDrive/Model/columns.json'

columns = {
    'data_columns': [col.lower() for col in X1.columns]
}

# Menyimpan data ke dalam file JSON di path yang sudah ditentukan
with open(file_path, "w") as f:
    f.write(json.dumps(columns))